### PR TITLE
Feathr UI: Display feature key and transform expression in feature detail pages

### PR DESCRIPTION
**Pull request by blrchen**
This PRs update feature detail ui page to display key and transform expression information.

Staging site: https://brave-moss-045d2ce00.1.azurestaticapps.net

### CODE REVIEW

**Comment by blrchen** [comment]
Staging url: https://brave-moss-045d2ce00.1.azurestaticapps.net/

**Comment by hangfei** [comment]
No need to display other operators for non-swa feautures:

image

**Comment by hangfei** [comment]
There are both transform_expr and def_expr. This is confusing to understand.

**Comment by hangfei** [comment]
image

**Review by xiaoyongzhumsft — APPROVED** [review]

**Review by hangfei — APPROVED** [review]

**Review by xiaoyongzhumsft — APPROVED** [review]

**Review by xiaoyongzhu — APPROVED** [review]

**Pull request merged**
