### PR TITLE
Added delete api of Redis

### LINKED ISSUE #161: Add delete feature API in Redis
The FeathrClient provides API to access features but we don't provide APIs to delete them. Add a delete API to the client so users can delete the feature data at their will.

Redis-realted code is here: https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py#L353

### PR DESCRIPTION
**Pull request by ahlag**
Signed-off-by: Chang Yong Lik <theeahlag@gmail.com>

## Description
- Added delete feature API in Redis

Resolves #161 

## How was this patch tested?
Unit tested in Github Actions

## Does this PR introduce any user-facing changes?
Allows users to delete feature from Redis

### CODE REVIEW

**Comment by ahlag** [comment]
@hangfei 
I think this is a typo `self.redis_clint` and should be `self.redis_client`.

**Comment by ahlag** [comment]
@hangfei 
I am not sure why sometimes the features are able to materialize in Redis and sometimes in my test case.

Successful attempt with the same code:
https://github.com/linkedin/feathr/runs/6931371630?check_suite_focus=true

Unsuccessful attempt with the same code:
https://github.com/linkedin/feathr/runs/6931656518?check_suite_focus=true

**Comment by hangfei** [comment]
For redis, i believe it's a race condition. Sometimes other tests are also writing to the same store that causing issues.

**Comment by hangfei** [comment]
Let's re-run the tests a few times to see if it passes.

**Comment by ahlag** [comment]
@hangfei 
Yeah. Never thought about it. Thanks for the advice.

**Comment by xiaoyongzhu** [comment]
BTW those errors like 
` pyapacheatlas.core.util.AtlasException: {"requestId":"ef1cb8f8-3ded-4a8e-91a8-d36381ae45ba","errorCode":"ATLAS-400-00-00D","errorMessage":"feathr_source_v1.url : attribute delete not supported"}` should be irrelevant

**Comment by ahlag** [comment]
@xiaoyongzhu 
I am not sure why I cannot materialize the features in Redis.


> @hangfei I am not sure why sometimes the features were not able to materialize in Redis and sometimes in my test case below.
> 
> https://github.com/linkedin/feathr/blob/7095b304e76f6d78c9027916a7137b6359476e5c/feathr_project/test/test_feature_materialization.py#L174-L208
> 
> Successful attempt with the same code: https://github.com/linkedin/feathr/runs/6931371630?check_suite_focus=true
> 
> Unsuccessful attempt with the same code: https://github.com/linkedin/feathr/runs/6931656518?check_suite_focus=true

**Comment by xiaoyongzhu** [comment]
Thanks @ahlag , this PR looks good to me.

For the test failures, they should have been fixed. Do you mind merging main back to your branch?

**Comment by ahlag** [comment]
@xiaoyongzhu 
Not sure why the materialization in Redis doesn't work. 
https://github.com/linkedin/feathr/runs/7271993669?check_suite_focus=true

I also found this comment in some of the test cases. Seems like there is no check for writing to the online store.

https://github.com/linkedin/feathr/blob/6aa3459ac3c49275e07945898402bce1541145d2/feathr_project/test/test_pyduf_preprocessing_e2e.py#L91-L108

**Comment by ahlag** [comment]
@xiaoyongzhu  @hangfei 
Hey the test passed! Sorry for the hold up.

**Review by xiaoyongzhu — APPROVED** [review]

**Comment by xiaoyongzhu** [comment]
Thanks @ahlag !

**Review by hangfei — APPROVED** [review]
Sorry about the late review. 

Looks great. Appreciate your comprehensive tests!

**Pull request merged**
