### PR TITLE
UI: Add home page and project list page

### PR DESCRIPTION
**Pull request by blrchen**
## Description

This PR adds two new page in web UI:
- Home: a new home page provider quick links to projects, sources and features page, this page also provider links for user for getting started.
- Projects: a new project list page to allow user explore projects and quickly navigate to project feature list / lineage page.

Staging url to preview this PR: https://brave-moss-045d2ce00.1.azurestaticapps.net/

## How was this PR tested?

Test two newly added UI can display correctly in local devbox

## Does this PR introduce any user-facing changes?

- [ ] No. You can skip the rest of this section.
- [x] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Comment by xiaoyongzhu** [comment]
@blrchen can you paste a few screenshots?

**Comment by hangfei** [comment]
Thanks for the PR. 

Could you add instructions on how to view your changes in website or screenshots?

**Comment by blrchen** [comment]
I added the staging url in PR description. @hangfei  @xiaoyongzhu

**Comment by xiaoyongzhu** [comment]
A few comments:

1. seems the lineage UI is wrong. I saw this in previous snapshot so not sure if this is in the UI layer or not

https://brave-moss-045d2ce00.1.azurestaticapps.net/projects/feathr_ci_registry_9_14_711429/lineage

2. I remember we added the management page in the side bar before?

**Comment by blrchen** [comment]
> A few comments:
> 
> 1. seems the lineage UI is wrong. I saw this in previous snapshot so not sure if this is in the UI layer or not
> 
> https://brave-moss-045d2ce00.1.azurestaticapps.net/projects/feathr_ci_registry_9_14_711429/lineage
> 
> 2. I remember we added the management page in the side bar before?

@xiaoyongzhu , 1 is a known issue addressed in PR #593 , 2 is expected as this staging site does not have rbac enabled on backend. Currently management menu is only visible when backend has rbac enabled.

**Comment by xiaoyongzhu** [comment]
> > A few comments:
> > 
> > 1. seems the lineage UI is wrong. I saw this in previous snapshot so not sure if this is in the UI layer or not
> > 
> > https://brave-moss-045d2ce00.1.azurestaticapps.net/projects/feathr_ci_registry_9_14_711429/lineage
> > 
> > 2. I remember we added the management page in the side bar before?
> 
> @xiaoyongzhu , 1 is a known issue addressed in PR #593 , 2 is expected as this staging site does not have rbac enabled on backend. Currently management menu is only visible when backend has rbac enabled.

I see, thanks!

**Review by xiaoyongzhu — APPROVED** [review]

**Review by jainr — APPROVED** [review]

**Pull request merged**
