### PR TITLE
broken link fix and typo fix

### PR DESCRIPTION
**Pull request by Yuqing-cat**
Thanks for @ahlag 's contribution in https://github.com/linkedin/feathr/pull/414, we dig out more broken links.
This PR fixed all links according to: https://github.com/ahlag/feathr/runs/7115496370?check_suite_focus=true, except:
1. https://pypi.org/manage/project/feathr/
2. https://xxx.readthedocs.io/en/latest/feathr.html 
3. https://localhost:3000

Those 3 could be bypassed / ignored.

### CODE REVIEW

**Comment by ahlag** [comment]
@Yuqing-cat 
I think the following links can be bypassed using the command below.
```
https://pypi.org/manage/project/feathr/
https://xxx.readthedocs.io/en/latest/feathr.html
https://localhost:3000/
```

Command
`pytest --check-links --check-links-ignore "https://github.com/.*/pull/.*" CHANGELOG.md`

Ref: https://github.com/jupyterlab/pytest-check-links#--check-links-ignore

**Review by xiaoyongzhu — APPROVED** [review]

**Comment by Yuqing-cat** [comment]
> @Yuqing-cat I think the following links can be bypassed using the command below.
> 
> ```
> https://pypi.org/manage/project/feathr/
> https://xxx.readthedocs.io/en/latest/feathr.html
> https://localhost:3000/
> ```
> 
> Command `pytest --check-links --check-links-ignore "https://github.com/.*/pull/.*" CHANGELOG.md`
> 
> Ref: https://github.com/jupyterlab/pytest-check-links#--check-links-ignore

looks good, we can add them.

**Comment by ahlag** [comment]
@Yuqing-cat 
I can open up a PR and test the REGEX for the three links. Do you have any URLs on your mind that you would like to exclude in the future?

**Comment by Yuqing-cat** [comment]
> @Yuqing-cat I can open up a PR and test the REGEX for the three links. Do you have any URLs on your mind that you would like to exclude in the future?

That would be great, I've created an issue to track this follow up: https://github.com/linkedin/feathr/issues/417
For future exclude URLs, so far not. But if there are some common practices, we can follow :)

**Review by blrchen — APPROVED** [review]

**Pull request merged**
