### PR TITLE
add contribution text

### PR DESCRIPTION
**Pull request by chinmaytredence**
Add contribution text for Customer360 Notebook.

### CODE REVIEW

**Comment by hangfei** [comment]
Release candidate for v0.4.0

**Review by xiaoyongzhu — DISMISSED** [review]

**Comment by hangfei** [comment]
It's hard to review the diff for notebook. Could you write down in your description what cell has changed?

**Comment by chinmaytredence** [comment]
**The cell 2 text is changed from:**

This notebook illustrates the use of Feathr Feature Store to create one of the use case for Customer 360. This usecase predicts Sales amount by the Discount offered. It includes following steps:

**To**

This notebook illustrates the use of Feathr Feature Store to create one of the use case for Customer 360. This notebook was created to use Feathr Feature store in Tredence Inc. for a ML & AI based solution.

This usecase predicts Sales amount by the Discount offered. It includes following steps:

**The last cell is added with text:**

##### Contributed by Tredencians

Tredence, a data science solutions provider, focuses on delivering business outcomes powered through it's unique approach to bridging the gap between insight creation and business value realization. As an innovation driven company at the core, Tredence experiments with the latest technology offerings in the Open Source space, adopts it to industrialize for real world problem solving and contributes the learnings and best practices back to open source community. Tredence Studio team used Feathr feature store for solving data science use cases and features life cycle management activities.

**Comment by chinmaytredence** [comment]
@hangfei would you like to have a look. I found that there is a [plugin](https://github.com/apps/review-notebook-app) which could help for .ipynb file review

**Review by xiaoyongzhu — APPROVED** [review]

**Review by hangfei — APPROVED** [review]
Thanks for contributing the notebook.

**Pull request merged**
