### PR TITLE
Fixed CI error of document link checks

### LINKED ISSUE #608: Main branch ci linkcheck breaks with parse error
@ahlag , linkcheck ci run breaks in main branch. Here is an example link: https://github.com/linkedin/feathr/runs/8011026910?check_suite_focus=true. 

E   IndexError: list index out of range
=========================== short test summary info ============================
ERROR docs/samples/fraud_detection_demo.ipynb - IndexError: list index out of...
ERROR docs/samples/product_recommendation_demo.ipynb - IndexError: list index...
ERROR docs/samples/product_recommendation_demo_advanced.ipynb - IndexError: l...
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 2.28s ===============================
Error: Process completed with exit code 2.

This seems a parser error, could you please help take a look?

### PR DESCRIPTION
**Pull request by ahlag**
Signed-off-by: changyonglik <theeahlag@gmail.com>

## Description

Fixed CI error of document link checks
Resolves #608

## How was this PR tested?

Running the following command to fix the code snippets.
```
pytest --check-links --check-links-cache --check-links-ignore "^https?:\/\/localhost(?:[:\/].+)?$" --check-links-ignore "^https?:\/\/pypi.org\/manage\/project\/feathr\/" docs
```

## Does this PR introduce any user-facing changes?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Make sure to clarify your proposed changes.

### CODE REVIEW

**Comment by ahlag** [comment]
@blrchen 
Could you review?

**Comment by ahlag** [comment]
As explained offline in our slack chat, the cause of the problem was that pytest-check-links cannot parse ~~~

Code section with ~~~
screen_shot 2022-08-25 at 23 41 46

When I changed ~~~ to ```
screen_shot 2022-08-25 at 23 43 02

The document check passed
screen_shot 2022-08-25 at 23 43 48

**Review by xiaoyongzhu — APPROVED** [review]

**Comment by blrchen** [comment]
@ahlag i see all notebook code intent changed to 1 whitespace (from 2 whitespaces), could you pls keep intent unchanged?

**Comment by ahlag** [comment]
@blrchen 
Ah sorry. I will recommit!

**Pull request closed without merging**
