### PR TITLE
build docker image for feathr

### PR DESCRIPTION
**Pull request by YihuiGuo**
This PR builds a docker image with feathr installed, and vscode server  / Jupyter lab integrated. 

To build the docker image, navigate to feathr root folder , 
image

To start the docker, you need to specify the port mapping. 
8080: vscode server
9090: jupyter lab

image

credential for jupyter lab and code server is "feathr"
image
image

### CODE REVIEW

**Review by jainr — APPROVED** [review]
Looks good to me, can you please add some documentation (with the screen shot you have in the PR description) under dev_guide explaining your motivation and steps to follow.

**Comment by YihuiGuo** [comment]
> Looks good to me, can you please add some documentation (with the screen shot you have in the PR description) under dev_guide explaining your motivation and steps to follow.

Sure, will update docs in this PR

**Comment by YihuiGuo** [comment]
@jainr  I updated dev guide, pls help review, thx

**Comment by xiaoyongzhu** [comment]
@YihuiGuo thanks for the PR, can you elaborate on the use case there? Like when would users need this image?

**Comment by windoze** [comment]
Which version of the Feathr client is integrated in this image? Can it be directly used in Jupyter notebook or users still need to install it by themselves?

**Comment by YihuiGuo** [comment]
> @YihuiGuo thanks for the PR, can you elaborate on the use case there? Like when would users need this image?

This image is built for feathr developers, make them able to create ephemeral and independent environment with feathr installed, and with powerful IDE ready to use. 
For example, getting rid of all pre-defined and legacy environment variables, and run feathr tests in a "clean environment".

**Comment by YihuiGuo** [comment]
> Which version of the Feathr client is integrated in this image? Can it be directly used in Jupyter notebook or users still need to install it by themselves?

It is using latest version of feathr . 
ref `RUN pip install git+https://github.com/linkedin/feathr.git#subdirectory=feathr_project`

Tested locally, feathr client can be directly used in notebook created by JupyterLab.

**Review by windoze — APPROVED** [review]

**Review by Yuqing-cat — APPROVED** [review]

**Pull request merged**
