### PR TITLE
Adding Bicep files for deployment

### PR DESCRIPTION
**Pull request by Dongbumlee**
Adding Bicep files based on previous ARM template.

### CODE REVIEW

**Review by xiaoyongzhu — DISMISSED** [review]

**Comment by xiaoyongzhu** [comment]
Thanks @Dongbumlee ! Can you add a few words for this bicep files (like how to use them etc. ) in this dev guide? https://github.com/linkedin/feathr/blob/main/docs/dev_guide/cloud_resource_provision.md

**Comment by Dongbumlee** [comment]
Sure, let me follow it up!

> Thanks @Dongbumlee ! Can you add a few words for this bicep files (like how to use them etc. ) in this dev guide? https://github.com/linkedin/feathr/blob/main/docs/dev_guide/cloud_resource_provision.md

**Comment by Dongbumlee** [comment]
Updated Deployment script to reducing the step.
Added code to retrieve user object id in the script and update document for Cloud Resource Provisioning

**Comment by xiaoyongzhu** [comment]
This is great PR. Thanks @Dongbumlee for the effort. I approved this PR but you probably need a follow up PR to update the path to the template:
```-TemplateUri https://raw.githubusercontent.com/Dongbumlee/feathr/main/docs/how-to-guides/deploy.json ```

**Review by xiaoyongzhu — APPROVED** [review]

**Review by hangfei — APPROVED** [review]

**Pull request merged**
