### PR TITLE
Fix test issues

### PR DESCRIPTION
**Pull request by xiaoyongzhu**
After @jainr 's earlier PR, the integration test when merging PRs into main branch won't run (due to they don't have labels). 
This PR is a temp fix for that, where have a separate test for main branch merging, and maintain all the original tests for pull_request and pull_request_target. 

There will be duplicated code (as pointed out by @jaymo001 ) and waiting for @jainr back to have an elegant fix.

### CODE REVIEW

**Comment by jaymo001** [comment]
Chat offline. Follow-up item: Richin will resolve the duplication in next PR.

**Review by jaymo001 — APPROVED** [review]

**Comment by xiaoyongzhu** [comment]
@jainr is OOF this week, fixing the bug to make sure main has test, and he can make it more elegant when he's back

**Comment by xiaoyongzhu** [comment]
Test failure is because of @windoze 's earlier PR. He's fixing it now

**Comment by hangfei** [comment]
Please follow https://github.com/linkedin/feathr/blob/main/docs/dev_guide/pull_request_guideline.md

**Review by hangfei — APPROVED** [review]

**Pull request merged**
